// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxlsgqitizupbnnpeaaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4bHNncWl0aXp1cGJubnBlYWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDgyMTQsImV4cCI6MjA2NjQyNDIxNH0.gC892O8nWM95V01c1Hr9g9yJD2eZufokZMriQdcZogo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);